name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  Configuration: Release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC token issuance for trusted publishing
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - name: Test
        run: |
          dotnet test --configuration ${{ env.Configuration }} --logger "trx;LogFileName=tests.trx" --results-directory ./artifacts/test-results -bl:./artifacts/logs/test.binlog

      - name: Pack
        if: always()
        run: |
          dotnet pack Meziantou.GitHubActionsTracing --configuration ${{ env.Configuration }} --output ./artifacts -bl:./artifacts/logs/pack.binlog

      - name: Upload NuGet packages
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: nuget-packages
          path: ./artifacts/*.nupkg
          retention-days: 1
          if-no-files-found: warn

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: build-tests-artifacts
          path: |
            ./artifacts/logs/*.binlog
            ./artifacts/test-results/**/*.trx
          retention-days: 1
          if-no-files-found: warn

      - name: NuGet login (OIDC â†’ temp API key)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: nuget/login@v1
        id: nuget-login
        with:
          user: meziantou

      - name: Push to NuGet.org
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        
      - name: Log in to Docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish server image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          dotnet publish ./Meziantou.GitHubActionsTracing.Server \
            --os linux \
            --arch x64 \
            --configuration ${{ env.Configuration }} \
            -p:PublishProfile=DefaultContainer
